language: go

install:
  - sudo apt install sbsigntool
  - sudo snap install core core18
  - sudo snap install --edge tpm2-simulator-chrisccoulson
  - ./get-deps
script:
  - ./run-tests --with-mssim
  - go vet ./...
